name: Deploy to Firebase Function via GitHub Action

on:
  push:
    branches:
      - main

env:
  CI: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x
          
      - name: Build Cloud Functions
        run: npm ci

      - name: Create Service Account Key
        run: echo '${{ secrets.SERVICE_ACCOUNT }}' > $HOME/gcloud.json

      - name: Deploy Cloud Functions
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
          npx firebase-tools deploy --only functions:authentication --project petszone-arg --debug
