name: Authentication Pets Zone Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2.4.3

      - name: Install npm packages
        run: |
          npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v0.3.0
        with:
          args: firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
